### ISSUE TITLE
Is there a simple telnet example ?

### ISSUE THREAD

**Issue by davecramer** [apple/servicetalk#2029]
I'd like to know where to start to implement a different blocking protocol, specifically postgres

**Comment by Scottmitch** [comment]
Our transport utilities are currently located in `io.servicetalk.transport.netty.*`. Here is a good place to start:
- client side [TcpConnector](https://github.com/apple/servicetalk/blob/main/servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpConnector.java)
- server side [TcpServerBinder](https://github.com/apple/servicetalk/blob/main/servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java)
- Netty to ServiceTalk reactive streams adapters: [DefaultNettyConnection](https://github.com/apple/servicetalk/blob/main/servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java)

Note these classes live in "internal" packages due to our focus being primarily on higher level protocols/features (h1, h2, gRPC, client side load balancing, active queue management / capacity management, ..). The implementations are battle tested but APIs subject to change/improve over time (feedback welcome).

Are you familiar with [r2dbc](https://r2dbc.io), and is your intention to target these style APIs?

**Comment by davecramer** [comment]
@Scottmitch Thx!

Yes, very familiar with r2dbc, no I'd like to just replace our blocking I/O with non-blocking I/O. There are some small issues in the driver which simply cannot be fixed without background processes. This may or may not be the way to go, but looks interesting.

**Comment by idelpivnitskiy** [comment]
Hi @davecramer!
Thanks for your question. Since the discussion does not continue, let me close the issue. If you have any follow-ups, feel free to comment here or open a new one.
