### ISSUE TITLE
SerializationException from `http-api` does not list `content-type`

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#878]
When users attempt to deserialize a response that has the wrong `content-type`, they receive an exception that lists all the headers, but with `<filtered>` as the value, making it hard to diagnose.

This may happen if the `content-type` is wrong, but the exception doesn’t include the `content-type`, so it’s hard to debug. This may also happen if the `content-type` is missing, such as often the case with a non-200 response.

We should enhance the message of `SerializationException` in `http-api` module to include the received `content-type` and `content-length` values.

Current message:
```
Unexpected headers, can not deserialize. Headers: DefaultHttpHeaders[content-type: <filtered>
content-length: <filtered>]
```
Desired message (with alternatives):
```
Unexpected headers, can not deserialize. DefaultHttpHeaders[content-type: text/plain
content-length: 12, some-other-header: <filtered>]
```
Header names that should not be filtered for `SerializationException`:
- content-type
- content-length
- transfer-encoding

**Comment by karim-elngr** [comment]
I would like to work on this issue, I did some investigation

1. Add a new debug filter `DEFAULT_DEBUG_HEADER_FILTER` to the `HeaderUtils` class which would be identical to `DEFAULT_HEADER_FILTER` except when the header entry key is one of [content-type, content-length, transfer-encoding].

2. Modify the following classes [`DefaultClassHttpDeserializer`, `DefaultTypeHttpDeserializer`, `FormUrlEncodedHttpDeserializer`, `HttpStringDeserializer`] and change the method `checkContentType` to call `headers.toString(DEFAULT_DEBUG_HEADER_FILTER)`. 
Note: I was thinking about refactoring and extracting `checkContentType` into `HeaderUtils` since the logic behind it is very similar in all cases, which is testing a predicate and throwing an exception, so we could add `checkContentType(HttpHeader, Predicate<HttpHeaders>)`

3. I am not sure how to handle the case where `content-type` is missing, I was thinking about modifying `HttpSerializationProviders` to account for missing `content-type` when creating the testing predicate, but I'm not sure what to text exactly. 
 
WDYT? Should I start working on it?

**Comment by idelpivnitskiy** [comment]
Hi @karim-elngr,

Thank you for the interest to contribute to ServiceTalk. Everything that you explained sounds reasonable to me. +1 for adding `checkContentType` utility because the implementation is identical everywhere. Good catch!

I see that there is also duplication in `DefaultClassHttpDeserializer` - `DefaultTypeHttpDeserializer` and `FormUrlEncodedHttpDeserializer` - `HttpStringDeserializer` that could be eliminated. But that could be a follow up, we don't need to mix it with existing issue.

Don't think we need a special case for 3. If there is no `content-type` header users will not see it in the list of headers. That should be enough.

Look forward to reviewing your PR.

**Comment by NiteshKant** [comment]
@karim-elngr great to see interest. We generally refrain from adding new public APIs in non-internal modules, so just make sure that the newly added method/constants to `HeaderUtils` are package private.

Otherwise the suggestions look reasonable, best of luck!
