### ISSUE TITLE
Update jersey to 2.30

### ISSUE THREAD

**Issue by NiteshKant** [apple/servicetalk#921]
New version of jersey is now available:

https://github.com/eclipse-ee4j/jersey/releases/tag/2.30

we should update the version and verify the following modules:

- servicetalk-http-router-jersey-internal
- servicetalk-http-router-jersey
- servicetalk-http-security-jersey
- servicetalk-data-jackson-jersey

**Comment by Mishail** [comment]
eclipse-ee4j/jersey#4380

**Comment by shekhar-rajak** [comment]
Should we update `jersey` version in the respective `gradle.properties` and check the test cases, right ?

**Comment by idelpivnitskiy** [comment]
@shekhar-rajak right, this will be the first step. But we may have not enough test coverage to catch the behavior difference (if any). Worth double checking the release notes [1] to understand what was changed.
Also, we need to wait for 2.30.1 release before upgrading because of the issue with JDK11 reported above.

[1] https://eclipse-ee4j.github.io/jersey.github.io/release-notes/2.30.html

**Comment by idelpivnitskiy** [comment]
Resolved in #959 
Thanks @ddossot ❤️
